---
name: Lint codebase

run-name: Linter triggered by @${{ github.actor }}

on:
  push:
    branches: "**"

  workflow_dispatch:
    inputs:
      fullProjectCheck:
        description: "Full project check"
        required: true
        default: false
        type: boolean
  
jobs:
  run-lint:  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Full git history is needed to get a proper list
          # of changed files within `super-linter`
          fetch-depth: 0

      - name: Useful information
        run: |
          echo "Linting full codebase? ${{ inputs.fullProjectCheck == 'true' }}"

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: ${{ inputs.fullProjectCheck == 'true' }}
          VALIDATE_BASH: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PYTHON: true
          VALIDATE_NATURAL_LANGUAGE: true
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
